### ISSUE TITLE
cases search seems flaky

### ISSUE THREAD

**Issue by michielbdejong** [tosdr/edit.tosdr.org#651] opened 2018-08-22 10:03 UTC
for instance searching for 'clearly' does not surface https://edit.tosdr.org/cases/278 and searching for 'service' only shows cases in one topic, which seems unlikely to be correct

**Comment by Vinnl** [comment] 2018-08-29 09:41
How often do you use the search and sorting options? Apart from listing only pending points (for which we now have the updated curator view), I'm somewhat inclined to just remove them altogether, to simplify the codebase and UX? Since we're listing all cases/services/etc anyway, Ctrl+F is equal in functionality to search - though I can imagine the search form (which is really just "filter") is more intuitive. I don't see the use case for sorting though. (On tosdr.org it might make sense.)

**Comment by madoleary** [comment] 2018-10-13 08:29
I think it's important to maintain search functionality. Average users aren't going to like using Ctrl+F to locate information. The problem is that the existing search bar isn't robust enough. I wonder if this wouldn't be a good opportunity to sprinkle some Vue onto the application. We could implement a Vue-based search component that would be way more powerful.

**Comment by JesseWeinstein** [comment] 2019-06-07 01:33
The Cases search bar also works differently than the others, in that it erases the search query when it reloads, which is very confusing (particularly as there is no Reset button to show all the entries again).

**Comment by madoleary** [comment] 2020-07-06 09:55
Resolved in most recent merge. Cases now searchable by both title and topic.

**Closed by madoleary** 2020-07-06 09:55 UTC
